name: CI Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        optimize-mode: [ReleaseSafe, ReleaseFast, ReleaseSmall, Debug]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: master
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-master

      - name: Build Summary
        run: zig build --summary all --verbose -Doptimize=${{ matrix.optimize-mode }}
      - name: Run
        run: |
            zig build test
            zig build run-example1 -Doptimize=${{ matrix.optimize-mode }}
            zig build run-example2 -Doptimize=${{ matrix.optimize-mode }}
            zig build run-example3 -Doptimize=${{ matrix.optimize-mode }}
            zig build run-example4 -Doptimize=${{ matrix.optimize-mode }}